[package]
name = 'ovbars'
publish = false
version = '0.1.1'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'ovbars'

[dependencies]
extendr-api = '*'
ovba = { git = "https://github.com/tim-weis/ovba", branch = "feature/path_sep" }
