[package]
name = 'ovbars'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'ovbars'

[dependencies]
extendr-api = '*'
ovba = "0.5.0"

[patch.crates-io]
ovba = { path = "vendor/ovba" }
