# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib ovbars, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if (is.null(e)) {
    return(NULL)
  }

  if (inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_ovbars__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_ovbars__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Returns a list of macro sources found in the vba binary.
#' The list is sorted alphabetically.
#' @param name the path to the input file
#' @export
`ovbar_out` <- function(`name`) {
  .Call(savvy_ovbar_out__impl, `name`)
}

#' Returns a list of additional meta data of directories found in the vba
#' binary. This is probably not useful for the user.
#' The list is sorted alphabetically.
#' @param name the path to the input file
#' @export
`ovbar_meta` <- function(`name`) {
  .Call(savvy_ovbar_meta__impl, `name`)
}
