# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_ovbars_wrappers", use_symbols = TRUE, package_name = "ovbars")

#' @usage NULL
#' @useDynLib ovbars, .registration = TRUE
NULL

#' Returns a list of macro sources found in the vba binary.
#' The list is sorted alphabetically.
#' @param name the path to the input file
#' @export
ovbar_out <- function(name) .Call(wrap__ovbar_out, name)

#' Returns a list of additional meta data of directories found in the vba
#' binary. This is probably not useful for the user.
#' The list is sorted alphabetically.
#' @param name the path to the input file
#' @export
ovbar_meta <- function(name) .Call(wrap__ovbar_meta, name)


# nolint end
